name: Price Gather
run-name: Price Gather
on:
  schedule:
    - cron: '0 9 * * *'
jobs:
  Daily_routine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Gatherer script
        uses: ./
        id: gather
      - name: commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
